LA = 100
MAX_NEIGHBORS = 6
MAX_TYPE = 3
CONCS = [0.3, 0.5, 0.0]

#OH
[[functional_groups]]
id = 0
count = 3

#NCO
[[functional_groups]]
id = 1
count = 3

#NCO
[[functional_groups]]
id = 2
count = 0

[[reactions]]
reactant1_id = 0
reactant2_id = 1
product1_id = 0
product2_id = 1
rate_constant = 10.0
bond = true

